services:
  - type: web
    name: seo-audit-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: DATABASE_URL
        value: mongodb+srv://nextwave:rCqoWHiiDUDGO8XT@cluster0.1pxs2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 # Replace with your actual MongoDB connection string
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true" # Prevents Puppeteer from re-downloading Chromium
    buildFilter:
      paths:
        - package.json
        - src/**
    plan: free
    initialDeployHooks:
      - npm install
      - npm install puppeteer
      - node node_modules/puppeteer/install.js
