services:
  - type: web
    name: seo-audit-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_PAGESPEED_API_KEY
        sync: false  # Add this to your environment variables in Render dashboard
      - key: GOOGLE_SEARCH_CONSOLE_API_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_API_KEY
        sync: false
    buildFilter:
      paths:
        - package.json
        - src/**
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    domains:
      - seo-audit-backend.onrender.com
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Accept, Authorization, Origin, X-Requested-With"